### ISSUE TITLE
Question about outputting event camera poses

### ISSUE THREAD

**Issue by wlxing1901** [tub-rip/cmax_slam#3]
First of all, I want to congratulate you on this excellent work and thank you for open-sourcing the code. The CMax-SLAM system looks very promising and the system's versatility across various scenarios are truly impressive. I'm excited to try it out.

I've been exploring the repository and have a question - I'm interested in **obtaining or saving the estimated event camera poses** from the system. However, I couldn't find a clear way to access or output these poses in the current implementation.

Is there a way to output or save the estimated camera poses? 

Thank you again for sharing this great work with the community. I appreciate any guidance you can provide on this.

**Comment by Shuang1997** [comment]
Hi, thanks for your interest in our work. To keep the code clean, we did not include the code for saving results.
To save the camera rotations, you can use `traj_->evaluate(t_sample)`, which returns a Sophus::SO3d variable, then you can easily convert it to quaternion or rotation vector for writing into txt files.

I copied an exmpale code segment here. You can adapt it to your needs and insert it in `processTimeWindow()`, after `setupProblemAndOptimize_gsl()`

// Write the poses sampled from the refined trajectory
ros::Time t_sample = t_win_beg_;
const ros::Time t_sample_end = t_win_beg_ + win_stride_;
const ros::Duration dt_sample = ros::Duration(0.02);  // 50Hz
while (t_sample < t_sample_end)
{
        const Sophus::SO3d pose_sample = traj_->evaluate(t_sample);
        const double t_pose = (t_sample - time_offset_).toSec();
        if (t_pose > 0) // Delete the poses before time offset
        {
              // Save poses in the format of quaternions
              const Eigen::Quaterniond quat = pose_sample.unit_quaternion();
              sampled_poses_writer_ << t_pose << " " << quat.x() << " " << quat.y() << " " << quat.z() << " " << quat.w() << std::endl;
         }
         t_sample += dt_sample;
}

**Comment by wlxing1901** [comment]
@Shuang1997 Thank you for your detailed response and the code snippet. This indeed allows for recording the poses, which is very helpful. I greatly appreciate your assistance.

However, I have a question regarding the **time_offset_** in the code segment. I'm not quite clear on what specific value this **time_offset_** represents.

I've made some modifications to the code, as shown below:

I've noticed that for a 5.0s event segment, I only end up with 4800 poses, corresponding to 4.8s. Could you help me understand why this is happening and if there's a way to ensure I capture the full 5.0s of poses?

`    void PoseGraphOptimizer::processTimeWindow(const AngVelMap &ang_vel_subset) {
        // Integrate angular velocity into frontend poses
        PoseMap frontend_poses = integrateAngVel(pose_latest_, ang_vel_subset);

        // Generate new control poses with front-end poses
        std::vector <Sophus::SO3d> ctrl_poses_new = traj_->generateCtrlPoses(frontend_poses,
                                                                             t_ang_vel_beg_,
                                                                             t_ang_vel_end_);
        // Add generated control poses to the trajectory
        // 1. For the first time window, add all generated control poses
        // 2. Otherwise, we need to remove the first 1/3 control poses for linear/cubic trajectory respectively
        if (first_time_window_) {
            VLOG(1) << "[processTimeWindow] First time window, add all generated control poses";

            // Fix the start of the trajectory
            if (params.traj_opt.spline_degree == 3)
                idx_cp_opt_beg_ = 3; // For cubic spline, fix the first three control poses
            else
                idx_cp_opt_beg_ = 1; // For linear spline, fix the first one control pose

            first_time_window_ = false;
        } else {
            const int num_cps_erase = (params.traj_opt.spline_degree == 3) ? 3 : 1;
            VLOG(4) << "[processTimeWindow] num_cps_erase = " << num_cps_erase;
            VLOG(4) << "[processTimeWindow] num ctrl_poses_new before erase = " << ctrl_poses_new.size();
            ctrl_poses_new.erase(ctrl_poses_new.begin(), ctrl_poses_new.begin() + num_cps_erase);
            VLOG(4) << "[processTimeWindow] num ctrl_poses_new after erase = " << ctrl_poses_new.size();
        }

        VLOG(4) << "[processTimeWindow] size traj before add = " << traj_->size();
        traj_->pushbackCtrlPoses(ctrl_poses_new);
        VLOG(3) << "[processTimeWindow] size traj after add = " << traj_->size();

        // Compute the index of the control pose within the time window
        // Fix the first N control pose (N is the degree of the trajectory)
        idx_cp_traj_beg_ = count_window_ * cp_stride_;
        idx_cp_opt_beg_ = std::max(idx_cp_traj_beg_, idx_cp_opt_beg_);
        num_cp_opt_ = traj_->size() - idx_cp_opt_beg_;

        // Set the number of fixed control poses in the current time window
        event_warper_->setNumFixedCtrlPoses(idx_cp_opt_beg_ - idx_cp_traj_beg_);
        // Set the start of the time window after sliding for event warper
        event_warper_->setNextWinBegTime(t_win_beg_ + win_stride_);

        // For updating alpha
        event_warper_->setFirstIter(true);

        // If the number of events in the current time window is too small,
        // the camera woule being stay still, so we do not perform BA
        if (event_subset_.size() > min_num_ev_per_win_) {
            // Perform CMax bundle adjustment for this time window
            VLOG(2) << "[Back-end] Perform CMax-BA for this time window";
            setupProblemAndOptimize_gsl();
            // Update the aligned global IWE
            event_warper_->updateIG();

            // Update updating times of each pixel on IG
            setUpdateTimesIG();
        } else {
            VLOG(1) << "[EventWarper::updateIG] event_subset_.size()=" << event_subset_.size()
                    << " < min_num_ev_per_win_=" << min_num_ev_per_win_
                    << ", camera nearly stays still";
        }


        // ***************************************
        // save trajectory
        // Write the poses sampled from the refined trajectory
        ros::Time t_sample = t_win_beg_;
        const ros::Time t_sample_end = t_win_beg_ + win_stride_;
        const ros::Duration dt_sample = ros::Duration(0.001); // 1000Hz

        std::cerr << "t_sample: " << t_sample << std::endl;
        std::cerr << "t_sample_end: " << t_sample_end << std::endl;
        std::cerr << "dt_sample: " << dt_sample << std::endl;
        std::cerr << "t_win_beg_: " << t_win_beg_ << std::endl;
        std::cerr << "win_stride_: " << win_stride_ << std::endl;
        Eigen::Quaterniond q( sqrt(0.5), 0, sqrt(0.5),0);
        Eigen::Matrix3d R = q.toRotationMatrix().inverse();

        while (t_sample < t_sample_end) {
            Sophus::SO3d pose_sample = traj_->evaluate(t_sample);
            pose_sample = Sophus::SO3d(R * pose_sample.unit_quaternion());
            const double t_pose = t_sample.toSec();
            if (t_pose > 0) // Delete the poses before time offset
            {
                ts_vec.emplace_back(t_pose);
                pose_vec.emplace_back(pose_sample);
            }
            t_sample += dt_sample;
        }

        this->writeToFile();
        // ***************************************


        // Update the latest pose, to prepare for the next time window
        pose_latest_.first = t_win_end_ - ros::Duration(1e-6);
        pose_latest_.second = traj_->evaluate(pose_latest_.first);
        ts_event_image_ = t_win_end_;

        // Publish the aligned global IWE
        if (params.data_opt.show_iwe)
            publishEventImage();
    }
`

**Comment by Shuang1997** [comment]
1. Time offset is the start time of the rosbags, for ECD datasets:
`time_offset_ = ros::Time(1468939802.884364206); // shapes_rotation
time_offset_ = ros::Time(1468940145.246817987); // poster_rotation
time_offset_ = ros::Time(1468940843.845407417); // boxes_rotation
time_offset_ = ros::Time(1473347265.928210508); // dynamic_rotation`

Substracting the time offset make the output poses starting from t=0, which is easier for comparing with GT.

2. CMax-SLAM works in a sliding window manner. In your case, the time window size is 0.2s. The condition to trigger the back-end to process the time window [t, t+0.2], is receiving an event that is later than t+0.2, because we need to make sure to receive all the data during this time window. For a 5s long data sequence, there is no event whose timestamp is bigger than 5, so the last time window would not be processed. If you really need poses for all the 5s, you can try to set a flag to identify the last time window and processs it without receiving later events. Or editting your rosbag by adding an event that is later than 5s, when it is received, the last time window would be processed.
